import React from "react";
import BackendLayout from "../../components/Layout/BackendLayout";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { Password } from "../../components/Profile";
// import { useDispatch, useSelector } from 'react-redux';

export default function Profile({ session }: { session: any }) {
  if (!session) return <></>;

  return (
    <>
      <Head>
        <title>Strategy Kiln - Profile</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-wrap">
        <div className="w-full lg:w-8/12 px-4">
          <div className="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-blueGray-100 border-0">
            <div className="rounded-t bg-white mb-0 px-6 py-6">
              <div className="text-center flex justify-between">
                <h6 className="text-blueGray-700 text-xl font-bold">Profile</h6>
              </div>
            </div>
            <div className="flex-auto px-4 lg:px-10 py-10 pt-0">
              <Password />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

Profile.Layout = BackendLayout;

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: { destination: `/auth/signin` },
    };
  }

  return {
    props: {
      session,
    },
  };
}
